services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sapienza_advisor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db/sapienza_advisor
    ports:
      - "8000:8000"

volumes:
  postgres_data:
