services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sapienza_advisor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth:
    build: ./Authentication  # Percorso corretto per il Dockerfile dell'Auth Service
    container_name: auth_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db/sapienza_advisor
    ports:
      - "8000:8000"

  user:
    build: ./UserManagement  # Percorso corretto per il Dockerfile del User Management Service
    container_name: user_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db/sapienza_advisor
    ports:
      - "8001:8001"

  faculty:
    build: ./FacultyManagement  # Percorso corretto per il Dockerfile del Faculty Service
    container_name: faculty_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db/sapienza_advisor
    ports:
      - "8002:8002"
  
  course:
    build: ./CourseManagement  # Percorso corretto per il Dockerfile del Course Service
    container_name: course_service
    restart: always
    depends_on:
      - db
      - faculty
    environment:
      DATABASE_URL: postgresql://postgres:admin@db/sapienza_advisor
    ports:
      - "8003:8003"


volumes:
  postgres_data:
